import { useState } from 'react'
import { ArrowUpRight, Gift, Heart, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import GiveKudosDialog from '../components/kudos/GiveKudosDialog'
import KudosCard from '../components/kudos/KudosCard'
import { currentUser, kudosFeed } from '../data/mockData'

function Dashboard() { const [dialogOpen, setDialogOpen] = useState(false); return <div className="space-y-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Tuesday, August 19, 2026</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Welcome back, Heer</h1><p className="mt-2 text-slate-500">Celebrate your teammates and recognize great work.</p></div><button className="primary-button" onClick={() => setDialogOpen(true)}><Gift size={18} />Give Kudos</button></div><div className="grid gap-4 md:grid-cols-3"><StatCard label="Giving allowance" value={`${currentUser.givingAllowance} / ${currentUser.allowanceTotal}`} detail="Points remaining" icon={<Gift />} /><StatCard label="Earned points" value={currentUser.earnedPoints} detail="Total recognition points" icon={<Sparkles />} /><StatCard label="Your impact" value={currentUser.kudosReceived} detail="Kudos received" icon={<Heart />} /></div><div className="grid gap-6 xl:grid-cols-[1fr_320px]"><section><div className="mb-4 flex items-center justify-between"><div><h2 className="section-title">Kudos feed</h2><p className="text-sm text-slate-500">See what your team is celebrating.</p></div><Link className="inline-flex items-center gap-1 text-sm font-semibold text-teal-700" to="/leaderboard">View leaderboard <ArrowUpRight size={16} /></Link></div><div className="space-y-4">{kudosFeed.map((kudos) => <KudosCard key={kudos.id} kudos={kudos} />)}</div></section><aside className="panel h-fit p-5"><p className="eyebrow">Recognition tip</p><h2 className="mt-2 text-xl font-bold text-slate-950">Make it specific.</h2><p className="mt-3 text-sm leading-6 text-slate-600">The best Kudos explain the impact someone made. A little detail makes appreciation memorable.</p><div className="mt-6 rounded-lg bg-slate-50 p-4 text-sm italic leading-6 text-slate-600">“Thanks for keeping the launch moving when the timeline changed.”</div></aside></div><GiveKudosDialog open={dialogOpen} onClose={() => setDialogOpen(false)} /></div> }
function StatCard({ label, value, detail, icon }) { return <div className="panel flex items-start justify-between p-5"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><span className="icon-tile">{icon}</span></div> }
export default Dashboard